### ISSUE TITLE
EnsureUniqueOperationIdsFilter 

### ISSUE THREAD

**Issue by ChivanTiebosch** [rbeauchamp/Swashbuckle.OData#70] opened 2016-02-16 16:14 UTC
We use our own logic to generate operation id's.It would be very helpfull if there would be an option to turn off the EnsureUniqueOperationIdsFilter when setting up Swashbuckle.OData in the Swagger pipeline.

Thanks in advance.

**Comment by joshbooker** [comment] 2016-02-19 14:49
Agree this would be helpful, but you can use your own logic to post-modify operIDs with a custom OperationFilter like so: https://github.com/rbeauchamp/Swashbuckle.OData/issues/52

**Comment by joshbooker** [comment] 2017-01-14 14:29
Revisiting this one. My earlier comment is incorrect. User operation filters do not override internal document filters since the internal doc filters post-modify user filters. Therefore the OP is correct and Ensure Unique cannot be prevented. The following issues a duplicate of this one. 
https://github.com/rbeauchamp/Swashbuckle.OData/issues/126

**Comment by rbeauchamp** [comment] 2017-04-24 17:57
Closing this old feature request as it is not important enough for someone to spend the time to implement it.

**Closed by rbeauchamp** 2017-04-24 17:57 UTC
Labels: enhancement, up-for-grabs
