### ISSUE TITLE
not able to update to current nuget Odata due to depend in Swashbuckle.OData

### ISSUE THREAD

**Issue by figuerres** [rbeauchamp/Swashbuckle.OData#105] opened 2016-09-01 15:27 UTC
trying to update to current Microsoft Odata to see if a bug is fixed in Microsoft's code.
but I can't here is the error message from the package manager

Attempting to gather dependency information for package 'Microsoft.OData.Core.7.0.0' with respect to project 'ADL.Web.Services', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'Microsoft.OData.Core.7.0.0' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Microsoft.OData.Core 7.0.0' is not compatible with 'Microsoft.AspNet.OData 5.9.1 constraint: Microsoft.OData.Core (> 6.14.0 && < 7.0.0)', 'Swashbuckle.OData 2.18.3 constraint: Microsoft.OData.Core (>= 6.14.0)'.

**Comment by rbeauchamp** [comment] 2016-10-06 20:41
Duplicate of #68. Should be fixed in https://www.nuget.org/packages/Swashbuckle.OData/2.18.8.

**Closed by rbeauchamp** 2016-10-06 20:41 UTC
Labels: duplicate
