### ISSUE TITLE
Issue with custom routing

### ISSUE THREAD

**Issue by darewreck54** [rbeauchamp/Swashbuckle.OData#29] opened 2015-12-21 20:22 UTC
I'm having issue displaying other custom route other then HttpMethod.Post & HttpMethod.Get

Controller signature:

public async Task<IHttpActionResult> Delete([FromODataUri] int customerId, [FromODataUri] int orderID)
{
  ...
}

public async Task<IHttpActionResult> Patch([FromODataUri] int customerId,[FromODataUri]  int orderID, Order order)
{
  ...
}

Config file:

 
config.AddCustomSwaggerRoute(customODataRoute, "/Customers({Id})/Orders/({orderID}")
    .Operation(HttpMethod.Delete)
    .PathParameter<int>("Id")
    .PathParameter<int>("orderID");

config.AddCustomSwaggerRoute(customODataRoute, "/Customers({Id})/Orders/({orderID}")
    .Operation(new HttpMethod("PATCH"))
    .PathParameter<int>("Id")
    .PathParameter<int>("orderID")
    .BodyParameter<Order>("order");

Thanks,
D

**Comment by darewreck54** [comment] 2015-12-23 02:36
I did some more research and debug the Swashbuckle.Odata code.  Figure i'll help debug the issue and make it easier for you.

 private static ODataPath GenerateSampleODataPath(ODataRoute oDataRoute, string sampleODataAbsoluteUri)
        {
            var oDataPathRouteConstraint = oDataRoute.GetODataPathRouteConstraint();

            var model = oDataRoute.GetEdmModel();

            string route = ServiceRoot.AppendPathSegment(oDataRoute.RoutePrefix);

            ODataPath path = oDataPathRouteConstraint.PathHandler.Parse(model, route, sampleODataAbsoluteUri);
            return path;
        }

So the issue happens when it tries to Parse the IODataPathHandler.  For some reason it cannot convert the parameters:

ServiceRoute: "http://any/"
route: "http://any/odata"
sampleODataAbsoluteUri : "http://any/odata/Orders(42)/Customers"

It throws an ODataException with an error message "Bad Request - Error in query syntax.".

But it's able to parse this successfully:

ServiceRoute: "http://any/"
route: "http://any/odata"
sampleODataAbsoluteUri : "http://any/odata/Customers(42)/Orders"

 In the config file:

         config.AddCustomSwaggerRoute(customODataRoute, "/Customers({Id})/Orders")
                .Operation(HttpMethod.Post)
                .PathParameter<int>("Id")
                .BodyParameter<Order>("order");
            
            config.AddCustomSwaggerRoute(customODataRoute, "/Orders({orderID})/Customers")
            .Operation(HttpMethod.Post)
            .PathParameter<int>("orderID")
            .BodyParameter<Customer>("customer");

CustomersController:

  public Task<IHttpActionResult> Post([FromODataUri] int orderID, Customer customer)
        {
            throw new NotImplementedException();
        }

OrdersController:
    public async Task<IHttpActionResult> Post([FromODataUri] int customerId, Order order)
        {
            order.OrderId = SequentialGuidGenerator.Generate(SequentialGuidType.SequentialAtEnd);
            order.CustomerId = customerId;

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _db.Orders.Add(order);
            await _db.SaveChangesAsync();

            return Created(order);
        }

It's not clear what is missing in the model that is causing the exception to be thrown when it tries to parse the OData path.

**Comment by rbeauchamp** [comment] 2015-12-23 04:51
ok. thanks for the investigation! it helps.

**Comment by rbeauchamp** [comment] 2015-12-27 11:27
This configuration:
```
config.AddCustomSwaggerRoute(customODataRoute, "/Orders({orderID})/Customers")
        .Operation(HttpMethod.Post)
        .PathParameter<int>("orderID")
        .BodyParameter<Customer>("customer");
```
and this controller action:
```
        [ResponseType(typeof(Customer))]
        public Task<IHttpActionResult> Post([FromODataUri] int orderID, Customer customer)
        {
            throw new NotImplementedException();
        }
```

won't work because the Order entity has a primary key of type GUID.

I'll investigate the issue reported in your original post. I.e.,

> I'm having issue displaying other custom route other then HttpMethod.Post & HttpMethod.Get

**Comment by rbeauchamp** [comment] 2015-12-27 11:35
This path in your original post does not look correct:

> config.AddCustomSwaggerRoute(customODataRoute, "/Customers({Id})/Orders/({orderID}")

You don't have a closing parenthesis on the orderID... Maybe you don't even want the opening parenthesis?

**Comment by rbeauchamp** [comment] 2015-12-27 12:21
@darewreck54 A fix is available in v2.8.1. FYI, your custom route config should look like:
```
            config.AddCustomSwaggerRoute(customODataRoute, "/Customers({Id})/Orders({orderID})")
                .Operation(HttpMethod.Delete)
                .PathParameter<int>("Id")
                .PathParameter<Guid>("orderID");
```

and the OrdersController action:
```
        public async Task<IHttpActionResult> Delete([FromODataUri] int customerId, [FromODataUri] Guid orderID)
        {
            throw new NotImplementedException();
        }
```

See this [unit test](https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData.Tests/Fixtures/CustomRouteTests.cs#L45).

**Comment by darewreck54** [comment] 2015-12-29 00:55
Thanks,

config.AddCustomSwaggerRoute(customODataRoute, "/Customers({Id})/Orders({orderID})")
                        .Operation(new HttpMethod("PATCH"))
                        .PathParameter<int>("Id")
                        .PathParameter<Guid>("orderID")
                        .BodyParameter<Order>("order");
            

with action:

 public async Task<IHttpActionResult> Patch([FromODataUri] int customerId, [FromODataUri] Guid orderID, Order order)
        {
            throw new NotImplementedException();
        }

This will result in issues with the swagger UI.  Order Controller will not render at all.

**Comment by rbeauchamp-lendingtree** [comment] 2015-12-29 01:15
You're welcome,
I'll research the PATCH issue. Re-opening this issue.

> Also is there a better way for error handling

I'm working on some error handling now that might help. Yeah, it's sometimes hard for me (and users) to determine the root cause/scenario for an issue. Better handling will develop over time as the assumptions are understood and documented. Suggestions and, better yet, pull requests are welcome. Thanks!

**Comment by darewreck54** [comment] 2015-12-29 07:29
Actually, I found the problem.  It deals with the CustomNavigationPropertyRoutingConvention class and how you have to specify the correct parameters for each controller.  

This is the updated code to make the new test changes I put above:

else if (typeof(OrdersController) == controllerType)
            {
                if (odataPath.PathTemplate.Equals("~/entityset/key/navigation")) //POST OR GET
                {
                    controllerContext.RouteData.Values["customerID"] = (odataPath.Segments[1] as KeyValuePathSegment).Value;
                    return controllerContext.Request.Method.ToString();
                }
                if (odataPath.PathTemplate.Equals("~/entityset/key/navigation/key")) //PATCH OR DELETE
                {
                    controllerContext.RouteData.Values["customerID"] = (odataPath.Segments[1] as KeyValuePathSegment).Value;

                    controllerContext.RouteData.Values["orderID"] = (odataPath.Segments[3] as KeyValuePathSegment).Value;
                    return controllerContext.Request.Method.ToString();
                }
            }

Notice the "orderID" matches with the controller Patch function and the configuration parameters in the  .PathParamter.

I guess when you use custom routing, with the way it's implemented you have to be very careful.

Thanks,
D

**Comment by rbeauchamp-lendingtree** [comment] 2015-12-30 01:11
As the root cause of the issue you mentioned and resolved isn't in the Swashbuckle.OData code base, I'm closing this issue. Thanks.

**Closed by rbeauchamp-lendingtree** 2015-12-30 01:11 UTC
Labels: bug

**Comment by bkwdesign** [comment] 2018-01-09 15:07
@darewreck54 - after 2 years now.. do you know if `AddCustomSwaggerRoute` now supports PATCH.. or is there a link you can post to the issue in the Swashbuckle.OData code base (was an issue opened?)

**Comment by darewreck54** [comment] 2018-01-09 17:43
Sorry, I moved to a different project and never had time to really resolve the issue or see if any updates addressed it.

You'll have to try it out to see if it’s still a problem.

I’ll keep you posted if I end up using the library again. Currently using .net core which doesn’t support odata fully yet.

Derek

On Jan 9, 2018, at 7:08 AM, Brian <notifications@github.com<mailto:notifications@github.com>> wrote:


@darewreck54<https://github.com/darewreck54> - after 2 years now.. do you know if AddCustomSwaggerRoute now supports PATCH.. or is there a link you can post to the issue in the Swashbuckle.OData code base (was an issue opened?)

**Comment by bkwdesign** [comment] 2018-01-09 20:54
The other side of the coin is correctly describing custom PATCH actions in WebApiConfig.cs using the `ODataConventionModelBuilder` - getting all the stars to align is a non-trivial task
