### ISSUE TITLE
Child Collections of ODataController in Swagger UI

### ISSUE THREAD

**Issue by nealeduncan** [rbeauchamp/Swashbuckle.OData#67] opened 2016-02-09 16:16 UTC
Child collections are not shown for ODataControllers.

In the example here: http://swashbuckleodata.azurewebsites.net/swagger/ui/index

The Customers ODataController resource does not show that in the GET, that Orders is available. It only shows primitive types (string, int etc).

The ApiController resource shows child resources (in the example Projects is a child collection of Client GET ApiController).

Can child collections be added to ODataControllers please?

**Comment by bigred8982** [comment] 2016-02-09 16:41
I believe this is related to #58

**Comment by rbeauchamp-lendingtree** [comment] 2016-02-09 23:05
Yes, when #58 is implemented you can turn this 'feature' off. 

We got where we are today from [this](https://github.com/rbeauchamp/Swashbuckle.OData/issues/46#issuecomment-169122665) thought process.

In summary:
Currently in the OData swagger model, by default we are displaying only top level primitive values to reflect what you will actually get back from OData if you don't do an $expand. (In WebApi, on the other hand, you will get back the full serialized graph, so by default we display the full graph in the WebApi swagger model. There is no 'expand' concept.)

Closing this as a duplicate of #58.

**Closed by rbeauchamp-lendingtree** 2016-02-09 23:05 UTC
Labels: duplicate
