### ISSUE TITLE
Issue with odata routes that contain route prefixes with parameters

### ISSUE THREAD

**Issue by wbreza** [rbeauchamp/Swashbuckle.OData#57] opened 2016-01-20 20:40 UTC
If a ODataRoute is registered with a route prefix that contains parameters I received the following exception when requesting the swagger route.

Ex) Within a WebApiConfig class or similar
```
config.MapODataServiceRoute(
    routeName: "ODataRoute",
    routePrefix: "{version}/{tenant}",
    model: builder.GetEdmModel()
);
```

**Exception Message**
The path variable 'VERSION' in the UriTemplate must be bound to a non-empty string value. Parameter name: parameters

**Stack Trace**
at System.UriTemplate.VariablesCollection.LoadDefaultsAndValidate(String[] normalizedParameters, Int32& lastNonDefaultPathParameter, Int32& lastNonNullablePathParameter) at System.UriTemplate.VariablesCollection.ProcessDefaultsAndCreateBindInfo(Boolean omitDefaults, String[] normalizedParameters, IDictionary`2 extraParameters, BindInformation& bindInfo) at System.UriTemplate.VariablesCollection.PrepareBindInformation(IDictionary`2 parameters, Boolean omitDefaults) at System.UriTemplate.BindByName(Uri baseAddress, IDictionary`2 parameters, Boolean omitDefaults) at Swashbuckle.OData.Descriptions.OperationExtensions.GenerateSampleODataAbsoluteUri(Operation operation, String serviceRoot, String pathTemplate) at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.CreateHttpRequestMessage(HttpMethod httpMethod, Operation potentialOperation, String potentialPathTemplate, ODataRoute oDataRoute, HttpConfiguration httpConfig) at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(HttpMethod httpMethod, Operation potentialOperation, String potentialPathTemplate, ODataRoute oDataRoute, HttpConfiguration httpConfig) at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig) at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.<>c__DisplayClass3_0.<Generate>b__1(SwaggerRoute potentialSwaggerRoute) at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext() at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext() at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext() at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext() at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source) at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions() at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion) at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion) at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken ) at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()

**Comment by rbeauchamp-lendingtree** [comment] 2016-01-20 23:03
@wbreza Thanks for opening this ticket and providing the details. Definitely haven't tested this scenario.

**Comment by rbeauchamp-lendingtree** [comment] 2016-01-23 22:51
@wbreza Now that I'm researching this issue, I'm guessing that you would want the Swagger UI to display and require input for path parameters named "version" and "tenant"? Can you provide or point me to enough sample code so I can write a unit test against a controller and action that utilizes this routePrefix? Thank you.

**Comment by rbeauchamp-lendingtree** [comment] 2016-01-25 17:40
Closing until we get more info on how to test.

**Comment by wbreza** [comment] 2016-01-25 18:34
In the event the {version} or {tenant} parameters are not defined then they should be treated like any other parameter withing the route.

In our particular use case we have predetermined values for what these could be.  I have a Swashbuckle document filter that runs and replaces these parameters based on known values.

**Comment by rbeauchamp-lendingtree** [comment] 2016-01-25 18:54
@wbreza So I would like to write a unit test for this: is there some open-source or sample code that i could grab? For example, here's a question: do the route values resolve to a particular versioned controller?, like:

```public class CustomersV1Controller : ODataController```

 or do they end up as parameters to an action?:, like:

```public IQueryable<Customer> GetCustomers(int version, string tenant)```

It would really help to have enough code to reproduce your issue and verify the results. Thanks!

**Comment by rbeauchamp-lendingtree** [comment] 2016-01-25 19:12
FYI, Swashbuckle.OData verifies that every potential route and path actually exists, so when building the swagger doc it always substitutes route and path parameters and internally submits a "mock" HttpRequestMessage to the OData infrastructure. It requires enough metadata at runtime to correctly substitute parameters and build a valid request. (for example, it would need to know that version is an int and tenant is a string, if that is the case).

**Comment by JAMSUPREME** [comment] 2016-02-02 17:45
Howdy, I have the same issue and I create a sample: https://github.com/JAMSUPREME/swashbuckle-odata-issue-57

Is there any way we can make Swashbuckle.Odata infer the type? I was thinking maybe `oDataRoute.Defaults` could be used for this purpose?

I'd appreciate any work-arounds/fixes you might have in mind. Let me know if you have any questions regarding the sample.

**Comment by rbeauchamp** [comment] 2016-02-02 17:49
Thanks @jamsupreme nice to have an example. I'll check it out and get back to you.

**Comment by rbeauchamp-lendingtree** [comment] 2016-02-08 04:30
@wbreza @JAMSUPREME  v2.14.0 now supports route prefixes that contain parameters. 

Please see the [documentation on this feature](https://github.com/rbeauchamp/Swashbuckle.OData#route-prefixes-that-have-parameters).

Give it a try and let me know if you find any issues. Thanks!

**Comment by arcanelore** [comment] 2016-03-07 17:53
How do I resolve this issue if the Route Prefix is an alphanumeric variable?

**Comment by rbeauchamp** [comment] 2016-03-08 00:35
what issue are you observing? i.e. what is the result if you try to use an alpha numeric route prefix?

**Comment by arcanelore** [comment] 2016-03-08 15:35
I am getting the Swagger UI, but I am getting a 500 returned when it tries to create/display the documentation. The error text is list below.

I created a simple project that shows the issue: [https://github.com/arcanelore/ODataSwaggerIssueRepro](Repro Project)

500 : {"Message":"An error has occurred.","ExceptionMessage":"The UriTemplate 'odata/v1/{testid}/TestModel({TestId})' is not valid; the UriTemplate variable named 'TestId' appears multiple times in the template. Note that UriTemplate variable names are case-insensitive. See the documentation for UriTemplate for more details.","ExceptionType":"System.InvalidOperationException","StackTrace":" at System.UriTemplate.VariablesCollection.AddPathVariable(UriTemplatePartType sourceNature, String varDeclaration, Boolean& hasDefaultValue)\r\n at System.UriTemplate.AddPathVariable(UriTemplatePartType sourceNature, String varDeclaration, Boolean& hasDefaultValue)\r\n at System.UriTemplateCompoundPathSegment.CreateFromUriTemplate(String segment, UriTemplate template)\r\n at System.UriTemplatePathSegment.CreateFromUriTemplate(String segment, UriTemplate template)\r\n at System.UriTemplate..ctor(String template, Boolean ignoreTrailingSlash, IDictionary`2 additionalDefaults)\r\n at System.UriTemplate..ctor(String template)\r\n at Swashbuckle.OData.Descriptions.OperationExtensions.GenerateSampleODataUri(Operation operation, String serviceRoot, String pathTemplate)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.CreateHttpRequestMessage(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)\r\n at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.<>c__DisplayClass3_0.<Generate>b__1(SwaggerRoute potentialSwaggerRoute)\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()\r\n at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()\r\n at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source)\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions()\r\n at System.Lazy`1.CreateValue()\r\n at System.Lazy`1.LazyInitValue()\r\n at System.Lazy`1.get_Value()\r\n at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions()\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} http://localhost:62165/swagger/docs/v1

**Comment by rbeauchamp** [comment] 2016-03-09 03:06
@arcanelore the stack trace indicates an issue with duplicate url parameter names. is it possible to change the parameter names such that 'testid' doesn't appear twice?

**Comment by arcanelore** [comment] 2016-03-09 05:52
@rbeauchamp I tracked down the duplicate URL Parameter. The issue was the that the Data Model Key field was the same name as the URL Parameter. I Changed the Url Parameter and that cleared the issue. Looks like everything is working. Thanks for the help.

**Comment by rbeauchamp** [comment] 2016-03-09 11:01
ok, good. your welcome!

**Comment by vantubbe** [comment] 2016-05-19 15:57
Hi, I updated to version 2.14 and am still experiencing this issue. I added the following lines to my startup, but still recieve the message "The path variable 'ROOTTENANTID' in the UriTemplate must be bound to a non-empty string value". Anything I may be missing?  Thanks in advance!

`var tenantRoute = config.MapODataServiceRoute("odataTenant", "api/odata/{rootTenantId}", tenantBuilder.GetEdmModel());
            tenantRoute.Constraints.Add("rootTenantId", new LongRouteConstraint());`

**Comment by rbeauchamp-lendingtree** [comment] 2016-05-19 16:27
@vantubbe Can you provide the URL used when you receive this message?

**Comment by rbeauchamp-lendingtree** [comment] 2016-05-19 16:35
Here's a unit test that demonstrates the usage: https://github.com/rbeauchamp/Swashbuckle.OData/blob/master/Swashbuckle.OData.Tests/Fixtures/ParameterizedRoutePrefixTests.cs#L25

**Comment by vantubbe** [comment] 2016-05-19 17:07
@rbeauchamp-lendingtree I am using /swagger/ui/index.  
Though as it runs through the urls I can see it hitting http://any/api/odata/42/SomeODataType(42) and getting a lot of 404s. I'm not sure which particular one is causing the 500 though.

**Comment by vantubbe** [comment] 2016-05-19 17:19
Found the cause I believe, it is when you have Actions on Entities that are using a route prefix variable.

If I comment out the following, the url returns successfully.

```csharp
ActionConfiguration approveCamp = camps.EntityType.Action("ApproveCamp");
```

**Comment by rbeauchamp-lendingtree** [comment] 2016-05-19 18:46
@vantubbe Ok, thanks. will try to reproduce the issue....

**Comment by vantubbe** [comment] 2016-06-02 22:54
I don't suppose you know a workaround for this in the meantime?  I'd really like to use this to document our api but unfortunately the actions/functions with the route prefixes seem to make break the app.  Thanks in advance for any advice!

**Comment by rbeauchamp** [comment] 2016-06-03 13:28
Sorry I don't; it will take some investigation. Happy to accept a pull report if you resolve the issue.

**Comment by vantubbe** [comment] 2016-10-05 19:41
I just wanted to add that I only get the error 

`The path variable 'ROOTTENANTID' in the UriTemplate must be bound to a non-empty string value.` 

when binding a function/action to and entity. When bound to an entity set, I am able to generate the documentation.  However, when I try to add unit tests to FunctionTests.cs, I get the above error regardless of whether bound to an entity or set.  I'd appreciate any suggestions you have in mind.

**Closed** 2016-10-06 19:37 UTC
Labels: bug, enhancement
